name: "coveralls"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Send coverage to coveralls
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - run: go mod download
      - run: >
          go test -race -covermode atomic -coverprofile=coverage.out ./...
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
        run: |
          go get github.com/mattn/goveralls
          echo $GOPATH
          ls -la $GOPATH/bin
          $GOPATH/bin/goveralls -coverprofile=coverage.out -service=github