name: "coveralls"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Send coverage to coveralls
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v1
        with:
          go-version: "1.18"
      - run: go mod download
      - run: >
          go test -race -covermode atomic -coverprofile=coverage.cov \
            . \
            ./pricelist/...
      - name: send coverage
        env:
          COVERALL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=coverage.cov -service=github